configured: false
soar: true
credentials:
  jhed:
    username: null
  github:
    email: null
    username: null
settings:
  github:
    core_editor: vi
    default_branch: main
  paths:
    python: /usr/local/bin/python3.10
    pip: /usr/local/bin/pip3.10
    home: /home/idies
    rstudio_config: /home/idies/.config
    workspace: /home/idies/workspace
    home_storage: /home/idies/workspace/home
    storage_parent: /home/idies/workspace/Storage/persistent
  volumes:
    user_home: //mtwfs.nas.jh.edu/HOME
    s_drive: //cloud.nas.jh.edu/sddesktop$
